# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Asistente.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AsistenteRegistros(object):
    def setupUi(self, AsistenteRegistros):
        AsistenteRegistros.setObjectName("AsistenteRegistros")
        AsistenteRegistros.setEnabled(True)
        AsistenteRegistros.resize(656, 475)
        AsistenteRegistros.setMinimumSize(QtCore.QSize(656, 475))
        AsistenteRegistros.setMaximumSize(QtCore.QSize(656, 475))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        AsistenteRegistros.setFont(font)
        self.centralwidget = QtWidgets.QWidget(AsistenteRegistros)
        self.centralwidget.setObjectName("centralwidget")
        self.Frame = QtWidgets.QFrame(self.centralwidget)
        self.Frame.setGeometry(QtCore.QRect(0, 40, 661, 251))
        self.Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame.setObjectName("Frame")
        self.List_MReg = QtWidgets.QListView(self.centralwidget)
        self.List_MReg.setGeometry(QtCore.QRect(400, 320, 241, 131))
        self.List_MReg.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.List_MReg.setObjectName("List_MReg")
        self.Bot_Reg = QtWidgets.QPushButton(self.centralwidget)
        self.Bot_Reg.setGeometry(QtCore.QRect(270, 340, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Bot_Reg.setFont(font)
        self.Bot_Reg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bot_Reg.setObjectName("Bot_Reg")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 290, 141, 21))
        self.label.setObjectName("label")
        self.Bot_HAnt = QtWidgets.QPushButton(self.centralwidget)
        self.Bot_HAnt.setGeometry(QtCore.QRect(0, 0, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Bot_HAnt.setFont(font)
        self.Bot_HAnt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bot_HAnt.setObjectName("Bot_HAnt")
        self.Bot_HSig = QtWidgets.QPushButton(self.centralwidget)
        self.Bot_HSig.setGeometry(QtCore.QRect(490, 0, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Bot_HSig.setFont(font)
        self.Bot_HSig.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bot_HSig.setObjectName("Bot_HSig")
        self.Label_hors = QtWidgets.QLabel(self.centralwidget)
        self.Label_hors.setGeometry(QtCore.QRect(170, 0, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Label_hors.setFont(font)
        self.Label_hors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_hors.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_hors.setObjectName("Label_hors")
        self.Bot_Sal = QtWidgets.QPushButton(self.centralwidget)
        self.Bot_Sal.setGeometry(QtCore.QRect(270, 410, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Bot_Sal.setFont(font)
        self.Bot_Sal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bot_Sal.setObjectName("Bot_Sal")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 300, 131, 31))
        self.label_2.setObjectName("label_2")
        self.Text_MatReg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_MatReg.setGeometry(QtCore.QRect(20, 340, 221, 31))
        self.Text_MatReg.setObjectName("Text_MatReg")
        AsistenteRegistros.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AsistenteRegistros)
        self.statusbar.setObjectName("statusbar")
        AsistenteRegistros.setStatusBar(self.statusbar)

        self.retranslateUi(AsistenteRegistros)
        QtCore.QMetaObject.connectSlotsByName(AsistenteRegistros)

    def retranslateUi(self, AsistenteRegistros):
        _translate = QtCore.QCoreApplication.translate
        AsistenteRegistros.setWindowTitle(_translate("AsistenteRegistros", "Asistente de Registros - By David Yánez"))
        self.Bot_Reg.setText(_translate("AsistenteRegistros", "Registrar"))
        self.label.setText(_translate("AsistenteRegistros", "Materias Registradas"))
        self.Bot_HAnt.setText(_translate("AsistenteRegistros", "Horario Anterior"))
        self.Bot_HSig.setText(_translate("AsistenteRegistros", "Horario Siguiente"))
        self.Label_hors.setText(_translate("AsistenteRegistros", "Horario"))
        self.Bot_Sal.setText(_translate("AsistenteRegistros", "Salir"))
        self.label_2.setText(_translate("AsistenteRegistros", "Materia a Registrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AsistenteRegistros = QtWidgets.QMainWindow()
    ui = Ui_AsistenteRegistros()
    ui.setupUi(AsistenteRegistros)
    AsistenteRegistros.show()
    sys.exit(app.exec_())
